### ISSUE TITLE
Black screen, unresponsive buttons on latest iOS build

### ISSUE THREAD

**Issue by lazerwalker** [veloce/lichobile#1138]
**I'm submitting a ...**  (keep the relevant one):
- bug report

# Bug report

**Current behavior:**

When I open the iOS app, the top-right button to show my active games is frequently (> 75% of the time) unresponsive. 

If I try to then open the side hamburger menu, probably 50% of the time I'm not signed in, but the "sign in" button is also nonresponsive. 

Whether or not the app thinks I am signed in, tapping most any other item in the hamburger menu results in the app showing a completely blank screen (100% black).

**Expected behavior:**

The top-right button shows me my active games.
I can consistently open the left hamburger menu, and see myself as logged in.
I can view other pages in the app without seeing a black screen.

**Steps to reproduce:**

1. Open the app. 
2. Try to tap the top-right icon to view games.
3. Try to open the left hamburger menu

**Environment information**

- iPhone 11 Pro (also occurs — albeit less often — on a 2018 iPad Pro 11.5")
- 13.3.3
- lichess v7.0.0

**Other information:**

I wish these repro steps were more helpful! Let me know if it's helpful for me to try to pull logs off of my device or something.

This anecdotally feels like it happens more often when I have limited internet connectivity, but it still occurs regularly when I have a strong connection.

**Comment by mhrichards** [comment]
Same problem. The IOS app is now so buggy that it is unusable.

**Comment by veloce** [comment]
I really have no idea with this bug. Does a full reinstall help?

**Comment by mhrichards** [comment]
Reinstall did not help. Impossible for me to invite my friends to a game.

Regards,
Mike Richards
Cell 832-876-2769

**Comment by americanhanko** [comment]
I'm experience the exact same behavior as @lazerwalker - using an iPhone Xs on iOS 13.3.1 (17D50) with version 7.0.1 — Reinstalling the app doesn't help.

Noticing that occasionally, it will take a while for me to get signed in (shows username in sidebar menu). Sometimes I never get signed in at all.

Where can I find the logs?

**Comment by colinluthier** [comment]
This has been a big struggle. I have not been able to complete a game since the update. Without the upper right button most of the game is unusable. It works sometimes right after opening the game. I can’t decide if this is one bug or many. 

1. Upper right button mostly unresponsive. 
2. Hitting home anytime but right after the app is started results in a black screen. 
3. Challenging a person I am following to a match locks the game.

**Comment by veloce** [comment]
have you the last version of the game, which is 7.0.3? and please send your iOS version.

**Comment by veloce** [comment]
Several people reported that deleting old lichess session on lichess website fixes the issue. See here: https://github.com/veloce/lichobile/issues/1129

**Comment by americanhanko** [comment]
@veloce v7.0.3 appears to have fixed the issue. Thanks!

**Comment by lazerwalker** [comment]
Is 7.0.3 available in all regions? I only see 7.0.2 on the iPhone US App Store.
 
![AA209D5A-CABD-4592-9868-3DB83F0CD377](https://user-images.githubusercontent.com/821238/75743649-9fff6a00-5cdf-11ea-9881-9ec6737695b1.png)

**Comment by veloce** [comment]
Yes, sorry if that is confusing. But I created the 7.0.2 version on apple store. Then I realised the 7.0.2 had a bug, and I increased the app version to 7.0.3 and submitted a new build. I found no way to delete the version on store, so I pushed the 7.0.3 build under the store 7.0.2.

You can check the actual version in the settings screen at the bottom.

**Comment by NaOHann** [comment]
Well I still have problem getting new version 😅
What should I do 😂

**Comment by dm-z** [comment]
@veloce Nothing works, new update requires iOS 12, my iOS 11 devices have 7.0 and non of modal screens work, they just dismissed when I try to interact with them. Browser works fine, app is broken since redesign. Is there an option to enable old interface which worked perfectly?
