### ISSUE TITLE
Advaced Search never returns any games

### ISSUE THREAD

**Issue by bcalmac** [veloce/lichobile#1229]
**I'm submitting a bug report** 

# Bug report

**Current behavior:**

Advanced search (for games) does not return any games. I can see the wheel spinning for 2-3 seconds but after it goes away no games are returned, irrespective of the filter. The same criteria works fine on the website. 

**Expected behavior:**

Return results matching search criteria. 

**Steps to reproduce:**

Go to Avanced Search, enter the criteria from the screenshot and tap Search. 

![515F6DCF-9617-483F-A7C3-70802DCA5A85](https://user-images.githubusercontent.com/3707379/81500381-c36a0680-9286-11ea-9170-93bfde4f0c52.png)

**Environment information**

- phone hardware iPhone Xs
- phone operating system version 13.4.1
- version of lichess mobile 7.0.5

**Comment by veloce** [comment]
Fixed now.

**Comment by bcalmac** [comment]
@veloce The problem is still there in 7.1.0. Was the fix  released in this version?
