### ISSUE TITLE
Rematch FEN steals En Passant

### ISSUE THREAD

**Issue by eyal282** [veloce/lichobile#1569]
**Describe the bug**
Rematching an FEN forgets the last move. This steals en passant, and may allow castling in a position where you shouldn't.

**To Reproduce**
1. Paste this FEN: "6nk/2p4p/3B1P1P/5KpP/8/8/8/8 w - g6 0 2"

2. En passant yourself to loss.
3. Rematch until you are white again.
4. Fail to En passant, as it is now an illegal move.

**Expected behavior**
Rematch won't steal your En Passant.

**Comment by jas14** [comment]
Can repro. I think this is a server issue. All we do is indicate to the server that we want a rematch - we don't specify the FEN.

https://github.com/veloce/lichobile/blob/b4d416b6ab6fd79bccc4c5527f34c7d9aa4a0248/src/ui/shared/round/view/button.tsx#L255-L258

**Comment by veloce** [comment]
That'd be nice to try reproduce on the website as well and post this issue to ornicar/lila if needed.

**Comment by hi-ogawa** [comment]
I can reproduce the same bug on website as well, so I'll make an issue there.

**Comment by ornicar** [comment]
The server side fix was merged.

**Comment by eyal282** [comment]
> The server side fix was merged.

The bug still works. "Play with the computer", then post FEN, then same of above
