### ISSUE TITLE
google play icon broken

### ISSUE THREAD

**Issue by pdknsk** [veloce/lichobile#267]
A minor bug on http://lichess.org/mobile.
```
404: https://developer.android.com/images/brand/en_app_rgb_wo_60.png
```

**Comment by ornicar** [comment]
fixed

**Comment by pdknsk** [comment]
Still broken here. I considered caching, but there isn't any on the main page.

**Comment by Unihedro** [comment]
wait for the next deploy, the changes has been published but the changes are not live yet.
