### ISSUE TITLE
App bug: Can't scroll up or down on the main screen

### ISSUE THREAD

**Issue by bspinto** [veloce/lichobile#874]
I'm submitting a bug report.

# Bug report

**Current behavior:**

 I can't scroll up or scroll down on the screen. I just can do this on the left side menu, but when it is closed, again the scrolling is no longer possible.

**Expected behavior:**

The screen should scroll up or down.

**Steps to reproduce:**

I open the app, and I can't scroll the screen up or down. If I open the side menu, scrolling works on it. But when it is closed, again the screen doesn't scroll. 

**Environment information**

- smartphone Alcatel_4060A
- Android version 5.1.1
-Lichess app version v6.0.4

**Comment by Webchessplayer** [comment]
I have the same problem and it's been there for a while. 
No scroll is all pages except the left side menu. 
So, I can't check the games history, or even in the analyses screen I can't scroll down to move the game back and forth. 
Android, Samsung.

**Comment by Webchessplayer** [comment]
Thanks a lot for the reply.
For some reason my Android System Webview was disabled. I enabled it and upgraded. 
Problem fixed! Lichess app works fine now.
I assume this is not really a Lichess app bug then, but a problem with android.

**Comment by bspinto** [comment]
Thank you very much.
It works now, problem fixed!

**Comment by naulau** [comment]
Same problem, but my android sistem webview is updated, I deleted lichess then restarted the phone then installed it but nothing, I can only scroll on the menu but everything else don't move. I have emui 4.0.3 with android 6.0

**Comment by jamespherman** [comment]
Same issue here. Android system webview was updated on 1/28/19, maybe that's why? I also tried clearing cache, deleting lichess app + reinstalling, no go.

**Comment by naulau** [comment]
Actually I just deleted the updates of system webview and the scroll is back, but I guess i need the updates for other apllication, and deleting then reinstalling them every time i want to use lichess is a bit odd to do

**Comment by pianowow** [comment]
I was able to fix this issue on Android 8.0 by uninstalling all Chrome updates, disabling Chrome, checking that android system webview is enabled, and then going back into Lichess.  I feel like this is kind of a nutty thing to have to do to run the Lichess app.

It appears that a recent update to Chrome and Android System Webview disabled Android System Webview.  I think apps are supposed to switch to Chrome to render webviews now instead of the Android System Webview.

**Comment by mlhtnc** [comment]
Same issue here. Except left side menu, scrolling is not working.

Android 7.1.1, Samsung J7 Prime 2
Chrome version: 72.0.3626.76

Then I disabled chrome as others suggested, it worked but I want my chrome up-to-date. So it's a hard way to make lichess working as expected.

Chrome version (after disabling): 63.0.3239.111

**Comment by sterlingbates** [comment]
Must be a recent update to Chrome that breaks this because Webview has been disabled for the past two years by some reports.

**Comment by mkoppen** [comment]
Scrolling works in the new version 6.1.1 but only on the main screen. Still not working for the other screens in the game or analyze mode. Except you uninstall the latest chrome update.

**Comment by niklasf** [comment]
Meanwhile @veloce found the Chrome bug that causes this: https://bugs.chromium.org/p/chromium/issues/detail?id=927066. A fix in Chrome is expected to land soon (and possibly also a [workaround](https://github.com/veloce/lichobile/compare/chrome72FlexBugWorkaround) in lichobile).

**Comment by Ilis** [comment]
It seems fixed in v. 9.1.1

**Comment by mlhtnc** [comment]
In analyse mode, scrolling is still does not work. Other parts work well, thanks for fix.
